name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.4.1'
          projectPath: anujshukla-aut/testingactions
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuiteCollectionPath="Test Suites/demo" -apiKey="ee58bf46-23ba-4752-9564-0e329ff60da5.API_KEY"  --config -webui.autoUpdateDrivers=true'
